RailsApp/config/routes.rb
Rails.application.routes.draw do

  resources :environments
  resources :settings
  resources :credentials
  resources :credentails
  resources :templates
  resources :users
  resources :posts
  root 'getdata#home'
  match "generateSpec" => "getdata#generateSpec", :via => :post, :as => :generateSpec
  get "downloadZip/:zip" , to: "getdata#sendZip"
  get "deactivate/:user_id", to: "users#deactivate"
  get "scheduledTemplates" , to: "templates#scheduledTemplates"
  get 'schedule/:job' , to: "templates#scheduleJob"
  get "getServers/:id" , :to => 'credentials#getServers'
  get "pauseJob/:job" , :to => 'templates#pauseJob'
  get 'getTestRail/:username' , :to => 'getdata#connectToTestRail'
  get 'logout' , :to  => 'getdata#logout'
  get 'jenkins_servers/:id' , :to => 'jenkins_servers#show'
  get 'app' , :to => 'dashboard#index'
  get 'insertTemplates' , :to => 'templates#create'
  get 'users' , :to => 'users#index'
  get 'getTemplates' , :to => 'templates#get'
  get 'autherize', :to => 'getdata#authorize'
  get 'getProfiles/:instance', :to => 'salesforce#getProfiles'
  get 'getUsers/:instance', :to => 'salesforce#getUsers'
  get 'buildJob/:options', :to => 'templates#runJob'
  #get 'deleteRow/:options', :to => 'getdata#deleteRow'
  #get 'application', :to => 'getdata#home'
  #get 'generateSpec/:specInfo' , to: "getdata#generateSpec"
  get 'application/advancedOptions', :to => 'dashboard#index'
  get 'goToApp', :to => 'getdata#goToApp'
  #get 'getdata/runspec', :to => 'getdata#runSpec'
  #get 'getParams' , :to => 'getdata#getParams'
  #get 'readFile' , :to => 'getdata#readFile'
  get 'getTestRailData/:dataToGet' , :to => 'getdata#getFromTestRail'
  #get 'getSalesforceInstances' , :to => 'getdata#getSalesforceInstances'
  #get 'insertData/:dataToInsert' , :to => 'getdata#insertData'
  resources :jenkins_servers
  get '*path' => 'application#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RailsApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RailsApp/app/models/credential.rb
class Credential < ApplicationRecord
end

RailsApp/app/models/environment.rb
class Environment < ApplicationRecord
end

RailsApp/app/models/jenkins_server.rb
class JenkinsServer < ApplicationRecord
end

RailsApp/app/models/product.rb
class Product < ApplicationRecord
end

RailsApp/app/models/salesforce_con.rb
class SalesforceCon < ApplicationRecord
end

RailsApp/app/models/setting.rb
class Setting < ApplicationRecord
end

RailsApp/app/models/template.rb
class Template < ApplicationRecord
end

RailsApp/app/models/user.rb
class User < ApplicationRecord
end

RailsApp/app/controllers/jenkins_servers_controller.rb
class JenkinsServersController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :set_jenkins_server, only: [:show, :edit, :update, :destroy]

  # GET /jenkins_servers
  # GET /jenkins_servers.json
  def index
    render json: {status: 200, output:JenkinsServer.all }
  end

  # GET /jenkins_servers/1
  # GET /jenkins_servers/1.json
  def show
    render json: {status: 200, output: JenkinsServer.select(:name,:url,:os,:browser,:username).where(name: params[:id]).take}
  end

  # GET /jenkins_servers/new
  def new
    @jenkins_server = JenkinsServer.new
  end

  # GET /jenkins_servers/1/edit
  def edit
    render json: {status: 200, output:JenkinsServer.select(:name) }
  end

  # POST /jenkins_servers
  # POST /jenkins_servers.json
  def create
    begin
      @jenkins_server = JenkinsServer.new(jenkins_server_params)
      puts @jenkins_server.browser
      @jenkins_server.browser = params['browser']
      existsServer = JenkinsServer.where(:url => @jenkins_server.url)
      #@@res =  @@con.exec('SELECT * FROM "QAAuto"."Credentials" WHERE "Credentials"."type" = '+"'jenkins'")
      if existsServer.empty?
      EnziJenkinsUtility::JenkinsUtility.new(@jenkins_server.username, @jenkins_server.password, @jenkins_server.url)
        if @jenkins_server.save
          render json: {status: 200, output: JenkinsServer.all}
        else
          render json: {status: 500, output: "Error Occured !"}
        end
      else
        if existsServer.update(:name => @jenkins_server.name,:username => @jenkins_server.username,:password => @jenkins_server.password , :url => @jenkins_server.url,:os => @jenkins_server.os,:browser => @jenkins_server.browser)
          render json: {status: 200, output: JenkinsServer.all}
        else
          render json: {status: 500, output: "Update Failed !"}
        end
      end
    rescue Exception => exp
      render json: {status: 500, output: "Invalid username or password !"}
    end
  end

  # PATCH/PUT /jenkins_servers/1
  # PATCH/PUT /jenkins_servers/1.json
  def update
    respond_to do |format|
      if @jenkins_server.update(jenkins_server_params)
        format.html { redirect_to @jenkins_server, notice: 'Jenkins server was successfully updated.' }
        format.json { render :show, status: :ok, location: @jenkins_server }
      else
        format.html { render :edit }
        format.json { render json: @jenkins_server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jenkins_servers/1
  # DELETE /jenkins_servers/1.json
  def destroy
    if JenkinsServer.where(:name => params['id']).take.destroy
      index()
    else
      render json: {status: 500, output: "Invalid Input"}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jenkins_server
      @jenkins_server = JenkinsServer.where(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jenkins_server_params
      params.require(:jenkins_server).permit(:browser,:name, :username, :password, :url, :os)
    end
end

RailsApp/app/helpers/application_helper.rb
module ApplicationHelper
end

RailsApp/app/helpers/credentails_helper.rb
module CredentailsHelper
end

RailsApp/app/helpers/credentials_helper.rb
module CredentialsHelper
end

RailsApp/app/helpers/dashboard_helper.rb
module DashboardHelper
end

RailsApp/app/helpers/environments_helper.rb
module EnvironmentsHelper
end

RailsApp/app/helpers/jenkins_servers_helper.rb
module JenkinsServersHelper
end

RailsApp/app/helpers/oauth_helper.rb
module OauthHelper
end

RailsApp/app/helpers/posts_helper.rb
module PostsHelper
end

RailsApp/app/helpers/salesforce_helper.rb
module SalesforceHelper
end

RailsApp/app/helpers/settings_helper.rb
module SettingsHelper
end

RailsApp/app/helpers/templates_helper.rb
module TemplatesHelper
end

RailsApp/app/helpers/testOauth.rb
require 'google/apis/gmail_v1'
require 'googleauth'
require 'googleauth/stores/file_token_store'

require 'fileutils'
class Authenticate
OOB_URI = 'http://localhost:3000'
APPLICATION_NAME = 'Gmail API Ruby Quickstart'
CLIENT_SECRETS_PATH = 'client_secret.json'
CREDENTIALS_PATH = File.join(Dir.home, '.credentials',
                             "gmail-ruby-quickstart.yaml")
SCOPE = Google::Apis::GmailV1::AUTH_GMAIL_READONLY

##https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&client_id=388234064505-1tp3vms4afh8m2lc2d630oq7dr40st86.apps.googleusercontent.com&include_granted_scopes=true&redirect_uri=http://localhost:3000&response_type=code&scope=https://www.googleapis.com/auth/gmail.readonly
# Ensure valid credentials, either by restoring from the saved credentials
# files or intitiating an OAuth2 authorization. If authorization is required,
# the @@users's default browser will be launched to approve the request.
#
# @return [Google::Auth::UserRefreshCredentials] OAuth2 credentials
def self.authorize
  FileUtils.mkdir_p(File.dirname(CREDENTIALS_PATH))

  client_id = Google::Auth::ClientId.from_file(CLIENT_SECRETS_PATH)
  token_store = Google::Auth::Stores::FileTokenStore.new(file: CREDENTIALS_PATH)
  authorizer = Google::Auth::UserAuthorizer.new(
      client_id, SCOPE, token_store)
  user_id = 'default'
  credentials = authorizer.get_credentials(user_id)
  if credentials.nil?
    url = authorizer.get_authorization_url(
        base_url: OOB_URI)


    code = gets
    credentials = authorizer.get_and_store_credentials_from_code(
        user_id: user_id, code: code, base_url: OOB_URI)
  end
  return url
end
end

RailsApp/app/helpers/users_helper.rb
module UsersHelper
end

RailsApp/app/views/jenkins_servers/_form.html.erb
<%= form_with(model: jenkins_server, local: true) do |form| %>
  <% if jenkins_server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(jenkins_server.errors.count, "error") %> prohibited this jenkins_server from being saved:</h2>

      <ul>
      <% jenkins_server.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :jenkins_server_name %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :jenkins_server_username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :jenkins_server_password %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :jenkins_server_url %>
  </div>

  <div class="field">
    <%= form.label :os %>
    <%= form.text_field :os, id: :jenkins_server_os %>
  </div>

  <div class="field">
    <%= form.label :browser %>
    <%= form.text_field :browser, id: :jenkins_server_browser %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

RailsApp/app/views/jenkins_servers/edit.html.erb
<h1>Editing Jenkins Server</h1>

<%= render 'form', jenkins_server: @jenkins_server %>

<%= link_to 'Show', @jenkins_server %> |
<%= link_to 'Back', jenkins_servers_path %>

RailsApp/app/views/jenkins_servers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jenkins Servers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Username</th>
      <th>Password</th>
      <th>Url</th>
      <th>Os</th>
      <th>Browser</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jenkins_servers.each do |jenkins_server| %>
      <tr>
        <td><%= jenkins_server.name %></td>
        <td><%= jenkins_server.username %></td>
        <td><%= jenkins_server.password %></td>
        <td><%= jenkins_server.url %></td>
        <td><%= jenkins_server.os %></td>
        <td><%= jenkins_server.browser %></td>
        <td><%= link_to 'Show', jenkins_server %></td>
        <td><%= link_to 'Edit', edit_jenkins_server_path(jenkins_server) %></td>
        <td><%= link_to 'Destroy', jenkins_server, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Jenkins Server', new_jenkins_server_path %>

RailsApp/app/views/jenkins_servers/new.html.erb
<h1>New Jenkins Server</h1>

<%= render 'form', jenkins_server: @jenkins_server %>

<%= link_to 'Back', jenkins_servers_path %>

RailsApp/app/views/jenkins_servers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @jenkins_server.name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @jenkins_server.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @jenkins_server.password %>
</p>

<p>
  <strong>Url:</strong>
  <%= @jenkins_server.url %>
</p>

<p>
  <strong>Os:</strong>
  <%= @jenkins_server.os %>
</p>

<p>
  <strong>Browser:</strong>
  <%= @jenkins_server.browser %>
</p>

<%= link_to 'Edit', edit_jenkins_server_path(@jenkins_server) %> |
<%= link_to 'Back', jenkins_servers_path %>