RailsApp/config/routes.rb
Rails.application.routes.draw do

  resources :environments
  resources :settings
  resources :credentials
  resources :credentails
  resources :templates
  resources :users
  resources :posts
  root 'getdata#home'
  match "generateSpec" => "getdata#generateSpec", :via => :post, :as => :generateSpec
  get "downloadZip/:zip" , to: "getdata#sendZip"
  get "deactivate/:user_id", to: "users#deactivate"
  get "scheduledTemplates" , to: "templates#scheduledTemplates"
  get 'schedule/:job' , to: "templates#scheduleJob"
  get "getServers/:id" , :to => 'credentials#getServers'
  get "pauseJob/:job" , :to => 'templates#pauseJob'
  get 'getTestRail/:username' , :to => 'getdata#connectToTestRail'
  get 'logout' , :to  => 'getdata#logout'
  get 'jenkins_servers/:id' , :to => 'jenkins_servers#show'
  get 'app' , :to => 'dashboard#index'
  get 'insertTemplates' , :to => 'templates#create'
  get 'users' , :to => 'users#index'
  get 'getTemplates' , :to => 'templates#get'
  get 'autherize', :to => 'getdata#authorize'
  get 'getProfiles/:instance', :to => 'salesforce#getProfiles'
  get 'getUsers/:instance', :to => 'salesforce#getUsers'
  get 'buildJob/:options', :to => 'templates#runJob'
  #get 'deleteRow/:options', :to => 'getdata#deleteRow'
  #get 'application', :to => 'getdata#home'
  #get 'generateSpec/:specInfo' , to: "getdata#generateSpec"
  get 'application/advancedOptions', :to => 'dashboard#index'
  get 'goToApp', :to => 'getdata#goToApp'
  #get 'getdata/runspec', :to => 'getdata#runSpec'
  #get 'getParams' , :to => 'getdata#getParams'
  #get 'readFile' , :to => 'getdata#readFile'
  get 'getTestRailData/:dataToGet' , :to => 'getdata#getFromTestRail'
  #get 'getSalesforceInstances' , :to => 'getdata#getSalesforceInstances'
  #get 'insertData/:dataToInsert' , :to => 'getdata#insertData'
  resources :jenkins_servers
  get '*path' => 'application#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RailsApp/app/models/credential.rb
class Credential < ApplicationRecord
end

RailsApp/app/controllers/credentials_controller.rb
require 'restforce'
class CredentialsController < ApplicationController
  protect_from_forgery with: :null_session

  # GET /credentials
  # GET /credentials.json
  def index
    @credentials = Credential.all
  end

  def getServers
    tempDataHolder = []
    Credential.where(entity: params['id']).each do |server|
      tempDataHolder.push(server['username'])
    end
    puts tempDataHolder
    render json: { status: 200, output: tempDataHolder}
  end

  # GET /credentials/1
  # GET /credentials/1.json
  def show
    render json: { status: 200, output: Credential.where(username:  params['id']).select([:username,:hostName]).take}
  end

  # GET /credentials/new
  def new
    @credential = Credential.new
  end

  # GET /credentials/1/edit
  def edit
    if params['id'].eql?('jenkins')
      render json: { status: 200, output: Credential.where(entity:  params['id']).select([:hostName]).to_a}
      return
    else
      render json: { status: 200, output: Credential.where(entity:  params['id']).select([:username, :hostName])}
      return
    end
    render json: { status: 200, output: Credential.where(username:  params['id']).select([:username, :hostName])}

  end

  # POST /credentials
  # POST /credentials.json
  def create
    @credential = Credential.new(credential_params)
    puts @credential
    existsCredentail = Credential.where(:username => @credential.username)
    if existsCredentail.empty?
    if @credential.entity.eql?('salesforce')
      salesforceConObj = SalesforceCon.new
      salesforceConObj = SalesforceCon.all
      @@client = Restforce.new(username: @credential.username,
                               password: @credential.password,
                               host: 'test.salesforce.com',
                               client_id: salesforceConObj[0]['client_id'],
                               client_secret: salesforceConObj[0]['client_secret'],
                               grant_type: "password",
                               api_version: '41.0')
      begin
        userInfo = @@client.user_info.to_h
        if userInfo['active']
          if Setting.where(name: 'allowedProfiles')['profile'].include? @@client.query("SELECT Id, Profile.name FROM User WHERE Id = '#{userInfo['user_id']}'").current_page[0]['Profile']['Name']
            if  !Credential.where(hostName: @credential.hostName).take.nil?
            render json: { status: 500, output: 'User Already Exists !!'}
          else
              if @credential.save
                render json: { status: 200, output: Credential.where(entity:  @credential.entity).select([:username, :hostName]).as_json.values}
              else
                render json: { status: 500, output: "Credentilas invalid"}
              end
          end
          else
            render json: { status: 500, output: "Inactive User"}
          end
        else
          render json: { status: 500, output: "Profile Not Allowed"}
        end
      rescue Exception => exp
        puts exp
          render json: { status: 500, output: exp}
      end
    else
      if @credential.entity.eql?('jenkins')
        begin
          EnziJenkinsUtility::JenkinsUtility.new(@credential.username,@credential.password,@credential.hostName)
          if  !Credential.where(hostName: @credential.hostName).take.nil?
            render json: { status: 500, output: 'User Already Exists !!!'}
          else
            if @credential.save
              render json: { status: 200, output:  Credential.where(entity:  @credential.entity).select([:hostName]).to_a}
            else
              render json: { status: 500, output: "Credentilas invalid"}
            end
          end
        rescue Exception => exp
          render json: { status: 500, output: exp}
        end
      else
        if @credential.save
          render json: { status: 200, output:  Credential.where(entity:  @credential.entity).select([:username, :hostName]).to_a}
        else
          render json: { status: 500, output: "Credentilas invalid"}
        end
      end
    end
    else
      if existsCredentail.update(:username => @credential.username, :password => @credential.password, :hostName => @credential.hostName ,:entity => @credential.entity)
        render json: { status: 200, output:  Credential.where(entity:  @credential.entity).select([:username, :hostName]).to_a}
      else
        render json: { status: 500, output: "Credentilas invalid"}
      end
    end
  end

  # PATCH/PUT /credentials/1
  # PATCH/PUT /credentials/1.json
  def update
    respond_to do |format|
      if @credential.update(credential_params)
        format.html { redirect_to @credential, notice: 'Credential was successfully updated.' }
        format.json { render :show, status: :ok, location: @credential }
      else
        format.html { render :edit }
        format.json { render json: @credential.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credentials/1
  # DELETE /credentials/1.json
  def destroy
    @credential.destroy
    respond_to do |format|
      format.html { redirect_to credentials_url, notice: 'Credential was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credential
      @credential = Credential.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def credential_params
      params.require(:credential).permit(:username, :password, :entity, :hostName)
    end
end

RailsApp/app/helpers/credentials_helper.rb
module CredentialsHelper
end

RailsApp/app/views/credentials/_form.html.erb
<%= form_with(model: credential, local: true) do |form| %>
  <% if credential.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(credential.errors.count, "error") %> prohibited this credential from being saved:</h2>

      <ul>
      <% credential.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :credential_username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :credential_password %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type, id: :credential_type %>
  </div>

  <div class="field">
    <%= form.label :hostName %>
    <%= form.text_field :hostName, id: :credential_hostName %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

RailsApp/app/views/credentials/edit.html.erb
<h1>Editing Credential</h1>

<%= render 'form', credential: @credential %>

<%= link_to 'Show', @credential %> |
<%= link_to 'Back', credentials_path %>

RailsApp/app/views/credentials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Credentials</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th>Type</th>
      <th>Hostname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @credentials.each do |credential| %>
      <tr>
        <td><%= credential.username %></td>
        <td><%= credential.password %></td>
        <td><%= credential.type %></td>
        <td><%= credential.hostName %></td>
        <td><%= link_to 'Show', credential %></td>
        <td><%= link_to 'Edit', edit_credential_path(credential) %></td>
        <td><%= link_to 'Destroy', credential, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Credential', new_credential_path %>

RailsApp/app/views/credentials/new.html.erb
<h1>New Credential</h1>

<%= render 'form', credential: @credential %>

<%= link_to 'Back', credentials_path %>

RailsApp/app/views/credentials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @credential.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @credential.password %>
</p>

<p>
  <strong>Type:</strong>
  <%= @credential.type %>
</p>

<p>
  <strong>Hostname:</strong>
  <%= @credential.hostName %>
</p>

<%= link_to 'Edit', edit_credential_path(@credential) %> |
<%= link_to 'Back', credentials_path %>