RailsApp/config/routes.rb
Rails.application.routes.draw do

  resources :environments
  resources :settings
  resources :credentials
  resources :credentails
  resources :templates
  resources :users
  resources :posts
  root 'getdata#home'
  match "generateSpec" => "getdata#generateSpec", :via => :post, :as => :generateSpec
  get "downloadZip/:zip" , to: "getdata#sendZip"
  get "deactivate/:user_id", to: "users#deactivate"
  get "scheduledTemplates" , to: "templates#scheduledTemplates"
  get 'schedule/:job' , to: "templates#scheduleJob"
  get "getServers/:id" , :to => 'credentials#getServers'
  get "pauseJob/:job" , :to => 'templates#pauseJob'
  get 'getTestRail/:username' , :to => 'getdata#connectToTestRail'
  get 'logout' , :to  => 'getdata#logout'
  get 'jenkins_servers/:id' , :to => 'jenkins_servers#show'
  get 'app' , :to => 'dashboard#index'
  get 'insertTemplates' , :to => 'templates#create'
  get 'users' , :to => 'users#index'
  get 'getTemplates' , :to => 'templates#get'
  get 'autherize', :to => 'getdata#authorize'
  get 'getProfiles/:instance', :to => 'salesforce#getProfiles'
  get 'getUsers/:instance', :to => 'salesforce#getUsers'
  get 'buildJob/:options', :to => 'templates#runJob'
  #get 'deleteRow/:options', :to => 'getdata#deleteRow'
  #get 'application', :to => 'getdata#home'
  #get 'generateSpec/:specInfo' , to: "getdata#generateSpec"
  get 'application/advancedOptions', :to => 'dashboard#index'
  get 'goToApp', :to => 'getdata#goToApp'
  #get 'getdata/runspec', :to => 'getdata#runSpec'
  #get 'getParams' , :to => 'getdata#getParams'
  #get 'readFile' , :to => 'getdata#readFile'
  get 'getTestRailData/:dataToGet' , :to => 'getdata#getFromTestRail'
  #get 'getSalesforceInstances' , :to => 'getdata#getSalesforceInstances'
  #get 'insertData/:dataToInsert' , :to => 'getdata#insertData'
  resources :jenkins_servers
  get '*path' => 'application#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RailsApp/app/models/setting.rb
class Setting < ApplicationRecord
end

RailsApp/app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  protect_from_forgery with: :null_session

  # GET /settings
  # GET /settings.json
  def index
    render json: { status: 200, output:Setting.all}
  end
  # GET /settings/1
  # GET /settings/1.json
  #
  def show
    puts "-------------------------------------------------------"
    puts Setting.where(:name => params['id']).select(:name , :value).take.inspect
    render json: { status: 200, output:Setting.where(:name => params['id']).select(:name , :value).take}
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(setting_params)
    existsSetting  = Setting.where(:name => @setting.name)
    if existsSetting.empty?
      if @setting.save
        render json: { status: 200, output:Setting.where(name: @setting.name)}
      else
        render json: { status: 500, output:'Error occured while insertion'}
      end
    else
      if existsSetting.update(:name => @setting.name,:value => @setting.value)
        render json: { status: 200, output:Setting.all}
      else
        render json: { status: 500, output:'Update failed'}
      end
    end
  end

  # PATCH/PUT /settings/1
  # PATCH/PUT /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to @setting, notice: 'Setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to settings_url, notice: 'Setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.require(:setting).permit(:name, :value)
    end
end

RailsApp/app/helpers/settings_helper.rb
module SettingsHelper
end

RailsApp/app/views/settings/_form.html.erb
<%= form_with(model: setting, local: true) do |form| %>
  <% if setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :setting_name %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value, id: :setting_value %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

RailsApp/app/views/settings/edit.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<h1>Editing Setting</h1>

<%= render 'form', setting: @setting %>

RailsApp/app/views/settings/index.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<div class="slds-grid" style="margin-left: 20%">
  <div class="slds-grid--overflow">
<p id="notice"><%= notice %></p>
    <div role="dialog" tabindex="-1" aria-labelledby="header43" id="test-collection" class="slds-modal slds-scrollable&#45;&#45;y ng-class: action['modal']">
      <div class="slds-modal__container">
        <div class="slds-modal__header">
          <button class="slds-button slds-modal__close slds-button--icon-inverse" title="Close" ng-click="action['modal'] = 'slds-slide-up-close slds-backdrop--close';  username = '' ; password='';">
            <svg aria-hidden="true" class="slds-button__icon slds-button__icon--large">
              <use xlink:href="/assets/icons/utility-sprite/svg/symbols.svg#close"></use>
            </svg>
            <span class="slds-assistive-text">Close</span>
          </button>
          <h2 id="header43" class="slds-text-heading--medium">Add New Setting</h2>
        </div>
        <div class="slds-modal__content slds-p-around--medium">
          <div class="slds-panel__section">
            <form name="login">
              <div class="slds-form-element slds-m-bottom&#45;&#45;medium">
                <label class="slds-form-element__label" for="name">Name</label>
                <div class="slds-form-element__control">
                  <input id="name" type="text" ng-model="name" class="slds-input" placeholder="" required/>
                </div>
              </div>
              <div class="slds-form-element slds-m-bottom&#45;&#45;medium">
                <label class="slds-form-element__label" for="value">Value</label>
                <div class="slds-form-element__control">
                  <input id="value" type="text" ng-model="value" class="slds-input" placeholder="" required/>
                </div>
              </div>
              {{$error}}
            </form>
          </div>
        </div>
        <div class="slds-modal__footer">
          <button class="slds-button slds-button--destructive" ng-click="action['modal'] = 'slds-slide-up-close slds-backdrop--close' ;  name = '' ; value = '';">Cancel</button>
          <button class="slds-button slds-button--brand" ng-click="addSetting(name,value)" ng-disabled="!(name && value) ">Save</button>
        </div>
      </div>

    </div>
    <div class="slds-backdrop ng-class: action['modal']"></div>
    <div class="slds-grid slds-grid--pull-padded slds-m-bottom--xx-large">
      <div class="slds-float_left">
        <div class="slds-is-relative" style="height: 50%;width: 90%">
          <article class="slds-card">
            <div class="slds-card__header">
              <header class="slds-media slds-media_center slds-has-flexi-truncate">
                <div class="slds-media__figure">
                </div>
                <div class="slds-media__body">
                  <h2>
                    <button class="slds-button slds-button_icon">
                      <div class="slds-text-heading_small">Add New Setting</div>
                    </button>
                  </h2>

                </div>
              </header>
              <div class="slds-no-flex">

              </div>
            </div>
            <div class="slds-card__body slds-card__body_inner">
              <div class="slds-align_absolute-center" style="padding: 0.5rem; background-color: rgb(244, 246, 249);fill-opacity: initial">
                <div class="slds-no-flex">
                  <button class="slds-button slds-button_neutral" ng-click="action['modal'] = 'slds-slide-up-open slds-backdrop--open'">New</button>
                </div>
              </div>
            </div>
          </article>
        </div>
      </div>
    </div>

<h1>Settings</h1>

<table class="slds-table  slds-table--cell-buffer table-wrapper slds-truncate slds-max-medium-table--stacked" role="grid">
  <thead>
    <tr>
      <th>Name</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= setting.name %></td>
        <td><%= setting.value %></td>
        <td><%= link_to 'Show', setting %></td>
        <td><%= link_to 'Edit', edit_setting_path(setting) %></td>
        <td><%= link_to 'Destroy', setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<!--
<%#= link_to 'New Setting', new_setting_path %>-->
  </div>
</div>

RailsApp/app/views/settings/new.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<h1>New Setting</h1>

<%= render 'form', setting: @setting %>

<%= link_to 'Back', settings_path %>

RailsApp/app/views/settings/show.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @setting.name %>
</p>

<p>
  <strong>Value:</strong>
  <%= @setting.value %>
</p>

<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Back', settings_path %>